// Complete read-only deployment candidate. Not installed or publicly registered by this module.
const parameter = (name: string) => ({
  name,
  typeName: "STRING",
  optional: false,
  passByValue: true
})
export const configurationBcCtsApi = {
  functionName: "Z_ORVANTA_CFG_BC_CTS",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: ["IV_BC_SET", "IV_VERSION", "IV_REQUEST", "IV_TASK"].map(parameter),
  exportParameters: [
    "EV_CODE",
    "EV_SYSTEM",
    "EV_CLIENT",
    "EV_USER",
    "EV_REQUEST",
    "EV_TASK",
    "EV_CTS_VERSION",
    "EV_DATA_BASE64",
    "EV_DATA_BYTES",
    "EV_OBJECT_COUNT",
    "EV_KEY_COUNT",
    "EV_STRING_KEY_COUNT"
  ].map(parameter),
  tableParameters: [],
  source: [
    "TYPE-POOLS: trwbo.",
    "DATA: ls_request TYPE trwbo_request,",
    "      ls_header TYPE e070, ls_client TYPE e070c,",
    "      lt_headers TYPE STANDARD TABLE OF e070,",
    "      lt_clients TYPE STANDARD TABLE OF e070c,",
    "      lt_objects TYPE STANDARD TABLE OF e071,",
    "      lt_keys TYPE STANDARD TABLE OF e071k,",
    "      lt_string_keys TYPE STANDARD TABLE OF e071k_str,",
    "      ls_string_key TYPE e071k_str,",
    "      ls_object TYPE e071, ls_key TYPE e071k,",
    "      lv_request TYPE trkorr, lv_parent TYPE trkorr,",
    "      lv_table TYPE tabname, lv_count TYPE i,",
    "      lv_pass TYPE i, lv_root TYPE i,",
    "      lv_buffer TYPE xstring, lv_first TYPE xstring,",
    "      lv_hash TYPE string, lv_base64 TYPE string.",
    "CLEAR: ev_code, ev_system, ev_client, ev_user, ev_request,",
    "       ev_task, ev_cts_version, ev_data_base64, ev_data_bytes,",
    "       ev_object_count, ev_key_count, ev_string_key_count.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'. RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N' OR",
    "   iv_request <> 'GR2K923429' OR iv_task <> 'GR2K923430'.",
    "  ev_code = 'INPUT_INVALID'. RETURN.",
    "ENDIF.",
    '" 范围固定，禁止调用方选择任意表或传输容器。',
    "DO 5 TIMES.",
    "  CASE sy-index.",
    "    WHEN 1. lv_table = 'E070'.",
    "    WHEN 2. lv_table = 'E070C'.",
    "    WHEN 3. lv_table = 'E071'.",
    "    WHEN 4. lv_table = 'E071K'.",
    "    WHEN 5. lv_table = 'E071K_STR'.",
    "  ENDCASE.",
    "  AUTHORITY-CHECK OBJECT 'S_TABU_NAM'",
    "    ID 'TABLE' FIELD lv_table ID 'ACTVT' FIELD '03'.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'AUTHORIZATION_DENIED'. RETURN.",
    "  ENDIF.",
    "ENDDO.",
    '" 两次顺序读取固定请求及任务，不代表锁内事务快照。',
    "DO 2 TIMES.",
    "  lv_pass = sy-index.",
    "  REFRESH: lt_headers, lt_clients, lt_objects, lt_keys, lt_string_keys.",
    "  DO 2 TIMES.",
    "    lv_root = sy-index.",
    "    IF lv_root = 1. lv_request = iv_request.",
    "    ELSE. lv_request = iv_task. ENDIF.",
    "    SELECT COUNT( * ) FROM e071 INTO lv_count WHERE trkorr = lv_request.",
    "    IF lv_count > 128.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    SELECT COUNT( * ) FROM e071k INTO lv_count",
    "      WHERE trkorr = lv_request.",
    "    IF lv_count > 128.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    SELECT COUNT( * ) FROM e071k_str INTO lv_count",
    "      WHERE trkorr = lv_request.",
    "    IF lv_count > 128.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    CLEAR: ls_request, ls_header, ls_client.",
    "    CALL FUNCTION 'TR_READ_REQUEST'",
    "      EXPORTING iv_read_e070 = 'X' iv_read_e070c = 'X'",
    "        iv_read_objs_keys = 'X' iv_trkorr = lv_request",
    "      CHANGING cs_request = ls_request",
    "      EXCEPTIONS error_occured = 1 no_authorization = 2",
    "        error_message = 3 OTHERS = 4.",
    "    IF sy-subrc <> 0.",
    "      IF sy-subrc = 2. ev_code = 'AUTHORIZATION_DENIED'.",
    "      ELSE. ev_code = 'READ_FAILED'. ENDIF.",
    "      RETURN.",
    "    ENDIF.",
    '" 标准请求头省略部分 E070C 属性，此处保留完整原生行。',
    "    SELECT SINGLE * FROM e070 INTO ls_header WHERE trkorr = lv_request.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'HEADER_MISSING'. RETURN.",
    "    ENDIF.",
    "    SELECT SINGLE * FROM e070c INTO ls_client WHERE trkorr = lv_request.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'CLIENT_MISSING'. RETURN.",
    "    ENDIF.",
    "    IF ls_header-trstatus <> 'D' OR ls_header-as4user <> sy-uname OR",
    "       ls_header-korrdev <> 'CUST' OR ls_client-client <> sy-mandt OR",
    "       ls_client-tarclient <> space OR",
    "       ls_client-extended_state <> space OR",
    "       ls_client-overtaker <> space OR",
    "       ls_request-h-trkorr <> lv_request OR",
    "       ls_request-h-trstatus <> ls_header-trstatus OR",
    "       ls_request-h-as4user <> ls_header-as4user OR",
    "       ls_request-h-trfunction <> ls_header-trfunction OR",
    "       ls_request-h-strkorr <> ls_header-strkorr OR",
    "       ls_request-h-client <> ls_client-client.",
    "      ev_code = 'HEADER_SCOPE_INVALID'. RETURN.",
    "    ENDIF.",
    "    IF lv_root = 1.",
    "      IF ls_header-trfunction <> 'W' OR ls_header-strkorr <> space OR",
    "         ls_header-tarsystem <> 'GR3'.",
    "        ev_code = 'HEADER_SCOPE_INVALID'. RETURN.",
    "      ENDIF.",
    "      lv_parent = ls_header-trkorr.",
    "    ELSE.",
    "      IF ls_header-trfunction <> 'Q' OR",
    "         ls_header-strkorr <> lv_parent OR",
    "         ls_header-tarsystem <> space.",
    "        ev_code = 'HEADER_SCOPE_INVALID'. RETURN.",
    "      ENDIF.",
    "    ENDIF.",
    "    IF lines( ls_request-objects ) > 128 OR",
    "       lines( ls_request-keys ) > 128 OR",
    "       lines( ls_request-keys_str ) > 128.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    LOOP AT ls_request-objects INTO ls_object.",
    "      IF ls_object-trkorr <> lv_request.",
    "        ev_code = 'ENTRY_SCOPE_INVALID'. RETURN.",
    "      ENDIF.",
    "    ENDLOOP.",
    "    LOOP AT ls_request-keys INTO ls_key.",
    "      IF ls_key-trkorr <> lv_request.",
    "        ev_code = 'ENTRY_SCOPE_INVALID'. RETURN.",
    "      ENDIF.",
    "    ENDLOOP.",
    "    LOOP AT ls_request-keys_str INTO ls_string_key.",
    "      IF ls_string_key-trkorr <> lv_request.",
    "        ev_code = 'ENTRY_SCOPE_INVALID'. RETURN.",
    "      ENDIF.",
    "      IF strlen( ls_string_key-tabkey ) > 4096 OR",
    "         strlen( ls_string_key-key_lens ) > 4096.",
    "        ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "      ENDIF.",
    "    ENDLOOP.",
    "    APPEND ls_header TO lt_headers.",
    "    APPEND ls_client TO lt_clients.",
    "    APPEND LINES OF ls_request-objects TO lt_objects.",
    "    APPEND LINES OF ls_request-keys TO lt_keys.",
    "    APPEND LINES OF ls_request-keys_str TO lt_string_keys.",
    "  ENDDO.",
    "  EXPORT system = sy-sysid client = sy-mandt user = sy-uname",
    "    bc_set = iv_bc_set version = iv_version",
    "    request = iv_request task = iv_task",
    "    headers = lt_headers clients = lt_clients objects = lt_objects",
    "    keys = lt_keys string_keys = lt_string_keys",
    "    TO DATA BUFFER lv_buffer.",
    "  IF xstrlen( lv_buffer ) = 0 OR xstrlen( lv_buffer ) > 524288.",
    "    ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "  ENDIF.",
    "  IF lv_pass = 1. lv_first = lv_buffer.",
    "  ELSEIF lv_first <> lv_buffer.",
    "    ev_code = 'READ_CHANGED'. RETURN.",
    "  ENDIF.",
    "ENDDO.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_buffer",
    "  IMPORTING hashstring = lv_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "    error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'. RETURN.",
    "ENDIF.",
    "TRANSLATE lv_hash TO LOWER CASE.",
    "IF strlen( lv_hash ) <> 64 OR lv_hash CN '0123456789abcdef'.",
    "  ev_code = 'HASH_FAILED'. RETURN.",
    "ENDIF.",
    "CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'",
    "  EXPORTING input = lv_buffer IMPORTING output = lv_base64",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_base64 IS INITIAL.",
    "  ev_code = 'ENCODING_FAILED'. RETURN.",
    "ENDIF.",
    '" 仅发布完整核对后的结果；本函数不提交、不加锁、不改 CTS。',
    "ev_data_bytes = xstrlen( lv_buffer ). CONDENSE ev_data_bytes NO-GAPS.",
    "ev_object_count = lines( lt_objects ). CONDENSE ev_object_count NO-GAPS.",
    "ev_key_count = lines( lt_keys ). CONDENSE ev_key_count NO-GAPS.",
    "ev_string_key_count = lines( lt_string_keys ).",
    "CONDENSE ev_string_key_count NO-GAPS.",
    "ev_system = sy-sysid. ev_client = sy-mandt. ev_user = sy-uname.",
    "ev_request = iv_request. ev_task = iv_task.",
    "ev_cts_version = lv_hash. ev_data_base64 = lv_base64.",
    "ev_code = 'CTS_READ_OK'."
  ]
} as const

export const configurationBcCtsLayouts = {
  E070: "8a8e77c5943147bdb77fb9d10afc803e0e3a9e8a2a44f8178defca38c48449f1",
  E070C: "e6d5897c0588ee2e1720b7a9bd420c8a75efa6a5b2163266d0fdca864a722632",
  E071: "8e687e14b7e96d70a5dc568e95e06d1c00e8a4ac7bd02bd18d634890df2cf9a1",
  E071K: "f6da6a1556eaea9b3c3df7e4f065eca401cf53381578d2a7a4e1af518a368000",
  E071K_STR: "c0ed80a482355e0be761fd3236a5e2e2dc69e14dcf034d792316950657fe66fc"
} as const

export const configurationBcCtsDependencies = {
  TR_READ_REQUEST: {
    remoteEnabled: false,
    source: "d3b3b7c7d5b2c89a515fc758baa30ddbcad623e8733e6c35d5fc460d04b6c718",
    interface: "8f04a178b0d749f9e30c7d914c2ccf5a5e04c533acba1fd3c349436d4652fe7c"
  },
  TRINT_READ_REQUEST: {
    remoteEnabled: false,
    source: "f5cebb50274f01915d6d5d85a6b058ae417889380db50d44d672d3cbc80094c8",
    interface: "ad8a3c8352ef4b4615aef7648b9ffead28751f151789e726ac3007d27d2e555a"
  },
  TRINT_READ_REQUEST_HEADER: {
    remoteEnabled: false,
    source: "c9d5c7de38ab7c68af82ea2f4cd229d7ba1f7e5cc521738fc322cc65992ee090",
    interface: "d2633c0da475daf2af3533e586e6a7ef36ec0f4ac84c6c77503b8413923bb813"
  },
  TR_AUTHORITY_CHECK_DISPLAY: {
    remoteEnabled: false,
    source: "1bf1f040acd563e46f775fb2c0c354c75ea8cb494379243ec5ff0950b24c2be7",
    interface: "6d966c3affd105d7808a659b62fc4356106648016b0ceae864b550182e290574"
  },
  SCMS_BASE64_ENCODE_STR: {
    remoteEnabled: false,
    source: "4d23ea3348507f29194d3429ba8f9205f159187d38a6ff3cc56295fc295ffbd0",
    interface: "d7e534d1aac8fe64eff242d5cff1366e3dbdca88769d7a3f0f405f88a5e919c9"
  },
  CALCULATE_HASH_FOR_RAW: {
    remoteEnabled: false,
    source: "874f8e777eda4b72aecd34ab11153af0fe291ca777b8023c96c13c1119bfd458",
    interface: "9d0e795153f6118bb966e18c6d4bdbca7e66f927c75bfe8e9fcf22d4fb153779"
  }
} as const
