// ECC 7.31: reviewed, fixed BC Set conversion only; never activates.
export const configurationBcPreviewApi = {
  functionName: "Z_ORVANTA_CFG_BC_PREVIEW",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: [
    {
      name: "IV_BC_SET",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_SOURCE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_TARGET_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  exportParameters: [
    {
      name: "EV_CODE",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SYSTEM",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_CLIENT",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_USER",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SOURCE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_TARGET_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_CANDIDATE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_DIFFERENCES",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_ERROR_FIELD",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  tableParameters: [
    {
      name: "ET_T006",
      typeName: "T006",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006A",
      typeName: "T006A",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006B",
      typeName: "T006B",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006C",
      typeName: "T006C",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006D",
      typeName: "T006D",
      optional: false,
      passByValue: false
    }
  ],
  source: [
    "DATA: lt_values TYPE STANDARD TABLE OF scprvals,",
    "      lt_languages TYPE STANDARD TABLE OF scprvall,",
    "      ls_value TYPE scprvals, ls_language TYPE scprvall,",
    "      lt_fields TYPE STANDARD TABLE OF dfies,",
    "      ls_field TYPE dfies, ls_convert TYPE rsconvlite,",
    "      lv_table TYPE ddobjname, lv_lang TYPE spras,",
    "      lv_value TYPE scprvals-value, lv_code TYPE string,",
    "      lv_source TYPE string, lv_target TYPE string,",
    "      lv_system TYPE string, lv_client TYPE string,",
    "      lv_user TYPE string, lv_diffs TYPE string,",
    "      lv_status TYPE string, lv_index TYPE c LENGTH 1,",
    "      lv_layout TYPE string, lv_expected TYPE string,",
    "      lv_dcpfm TYPE usr01-dcpfm, lv_dcpfm_after TYPE usr01-dcpfm,",
    "      lv_present TYPE c, lv_found TYPE c, lv_rows TYPE i,",
    "      lv_count TYPE i, lv_length TYPE i, lv_row_index TYPE i,",
    "      lv_buffer TYPE xstring, lv_hash TYPE string,",
    "      lr_row TYPE REF TO data, lr_before TYPE REF TO data.",
    "FIELD-SYMBOLS: <row> TYPE any, <before> TYPE any,",
    "               <value> TYPE any, <old> TYPE any.",
    "DATA: lt_t006 TYPE STANDARD TABLE OF t006,",
    "      lb_t006 TYPE STANDARD TABLE OF t006,",
    "      ls_t006 TYPE t006,",
    "      lo_t006 TYPE t006.",
    "DATA: lt_t006a TYPE STANDARD TABLE OF t006a,",
    "      lb_t006a TYPE STANDARD TABLE OF t006a,",
    "      ls_t006a TYPE t006a,",
    "      lo_t006a TYPE t006a.",
    "DATA: lt_t006b TYPE STANDARD TABLE OF t006b,",
    "      lb_t006b TYPE STANDARD TABLE OF t006b,",
    "      ls_t006b TYPE t006b,",
    "      lo_t006b TYPE t006b.",
    "DATA: lt_t006c TYPE STANDARD TABLE OF t006c,",
    "      lb_t006c TYPE STANDARD TABLE OF t006c,",
    "      ls_t006c TYPE t006c,",
    "      lo_t006c TYPE t006c.",
    "DATA: lt_t006d TYPE STANDARD TABLE OF t006d,",
    "      lb_t006d TYPE STANDARD TABLE OF t006d,",
    "      ls_t006d TYPE t006d,",
    "      lo_t006d TYPE t006d.",
    '" 输出只在所有转换及复读通过后填充；没有配置写入。',
    "CLEAR: ev_code, ev_system, ev_client, ev_user,",
    "       ev_source_version, ev_target_version,",
    "       ev_candidate_version, ev_differences, ev_error_field.",
    "REFRESH et_t006.",
    "REFRESH et_t006a.",
    "REFRESH et_t006b.",
    "REFRESH et_t006c.",
    "REFRESH et_t006d.",
    "ev_system = sy-sysid.",
    "ev_client = sy-mandt.",
    "ev_user = sy-uname.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'.",
    "  RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N'",
    "OR strlen( iv_source_version ) <> 64",
    "OR strlen( iv_target_version ) <> 64",
    "OR iv_source_version CN '0123456789abcdef'",
    "OR iv_target_version CN '0123456789abcdef'.",
    "  ev_code = 'INPUT_INVALID'.",
    "  RETURN.",
    "ENDIF.",
    '" 整包原生版本固定，额外值、孤立值、通配键均改变此版本。',
    "IF iv_source_version <>",
    "  '73783f69f1bf9805b058fbc9bab0adb8cc8047f85c837ee16c174a9edd0f512b'.",
    "  ev_code = 'SOURCE_NOT_ATTESTED'.",
    "  RETURN.",
    "ENDIF.",
    "CALL FUNCTION 'Z_ORVANTA_CFG_BC_READ'",
    "  EXPORTING iv_bc_set = iv_bc_set iv_version = iv_version",
    "  IMPORTING ev_code = lv_code ev_system = lv_system",
    "    ev_client = lv_client ev_user = lv_user",
    "    ev_source_version = lv_source ev_target_version = lv_target",
    "  TABLES et_t006 = lb_t006 et_t006a = lb_t006a",
    "    et_t006b = lb_t006b et_t006c = lb_t006c et_t006d = lb_t006d",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_code <> 'READ_OK'.",
    "  ev_code = 'READ_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "IF lv_source <> iv_source_version OR lv_target <> iv_target_version",
    "OR lv_system <> 'GR2' OR lv_client <> '200' OR lv_user <> sy-uname.",
    "  ev_code = 'VERSION_CONFLICT'.",
    "  RETURN.",
    "ENDIF.",
    "LOOP AT lb_t006b INTO lo_t006b.",
    "  IF lo_t006b-msehi <> 'KNM'.",
    "    ev_code = 'ALIAS_CONFLICT'.",
    "    RETURN.",
    "  ENDIF.",
    "ENDLOOP.",
    "LOOP AT lb_t006c INTO lo_t006c.",
    "  IF lo_t006c-msehi <> 'KNM'.",
    "    ev_code = 'ALIAS_CONFLICT'.",
    "    RETURN.",
    "  ENDIF.",
    "ENDLOOP.",
    "SELECT SINGLE dcpfm INTO lv_dcpfm FROM usr01",
    "  WHERE bname = sy-uname.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'USER_FORMAT_UNAVAILABLE'.",
    "  RETURN.",
    "ENDIF.",
    "SELECT * FROM scprvals INTO TABLE lt_values UP TO 101 ROWS",
    "  WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "SELECT * FROM scprvall INTO TABLE lt_languages UP TO 101 ROWS",
    "  WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "DESCRIBE TABLE lt_values LINES lv_count.",
    "IF lv_count <> 41.",
    "  ev_code = 'SOURCE_CHANGED'.",
    "  RETURN.",
    "ENDIF.",
    "DESCRIBE TABLE lt_languages LINES lv_count.",
    "IF lv_count <> 18.",
    "  ev_code = 'SOURCE_CHANGED'.",
    "  RETURN.",
    "ENDIF.",
    '" 只预览标准 USE 更新策略；不调用装载、激活、日志或传输函数。',
    "DO 5 TIMES.",
    "  CASE sy-index.",
    "    WHEN 1.",
    "      lv_table = 'T006'.",
    "      lv_rows = 1.",
    "      lv_expected =",
    "        'MANDT|MSEHI|KZEX3|KZEX6|ANDEC|KZKEH|KZWOB|KZ1EH|KZ2' &&",
    "        'EH|DIMID|ZAEHL|NENNR|EXP10|ADDKO|EXPON|DECAN|ISOCOD' &&",
    "        'E|PRIMARY|TEMP_VALUE|TEMP_UNIT|FAMUNIT|PRESS_VAL|PR' &&",
    "        'ESS_UNIT'.",
    "    WHEN 2.",
    "      lv_table = 'T006A'.",
    "      lv_rows = 3.",
    "      lv_expected =",
    "        'MANDT|SPRAS|MSEHI|MSEH3|MSEH6|MSEHT|MSEHL'.",
    "    WHEN 3.",
    "      lv_table = 'T006B'.",
    "      lv_rows = 3.",
    "      lv_expected =",
    "        'MANDT|SPRAS|MSEH3|MSEHI'.",
    "    WHEN 4.",
    "      lv_table = 'T006C'.",
    "      lv_rows = 3.",
    "      lv_expected =",
    "        'MANDT|SPRAS|MSEH6|MSEHI'.",
    "    WHEN 5.",
    "      lv_table = 'T006D'.",
    "      lv_rows = 1.",
    "      lv_expected =",
    "        'MANDT|DIMID|LENG|MASS|TIMEX|ECURR|TEMP|MOLQU|LIGHT|' &&",
    "        'MSSIE|TEMP_DEP|PRESS_DEP'.",
    "  ENDCASE.",
    "  REFRESH lt_fields.",
    "  CALL FUNCTION 'DDIF_NAMETAB_GET'",
    "    EXPORTING tabname = lv_table",
    "    TABLES dfies_tab = lt_fields",
    "    EXCEPTIONS not_found = 1 error_message = 2 OTHERS = 3.",
    "  IF sy-subrc <> 0 OR lt_fields IS INITIAL.",
    "    ev_code = 'LAYOUT_UNAVAILABLE'.",
    "    RETURN.",
    "  ENDIF.",
    "  CLEAR lv_layout.",
    "  LOOP AT lt_fields INTO ls_field.",
    "    IF lv_layout IS INITIAL.",
    "      lv_layout = ls_field-fieldname.",
    "    ELSE.",
    "      CONCATENATE lv_layout ls_field-fieldname",
    "        INTO lv_layout SEPARATED BY '|'.",
    "    ENDIF.",
    "    IF ls_field-inttype NA 'CNIPFsb'",
    "    OR ls_field-datatype = 'CURR' OR ls_field-datatype = 'CUKY'.",
    "      ev_code = 'LAYOUT_UNSUPPORTED'.",
    "      RETURN.",
    "    ENDIF.",
    "  ENDLOOP.",
    "  IF lv_layout <> lv_expected.",
    "    ev_code = 'LAYOUT_CHANGED'.",
    "    RETURN.",
    "  ENDIF.",
    "  DO lv_rows TIMES.",
    "    lv_row_index = sy-index.",
    "    lv_index = lv_row_index.",
    "    CLEAR: lv_lang, lv_present.",
    "    CASE lv_row_index.",
    "      WHEN 1. lv_lang = '1'.",
    "      WHEN 2. lv_lang = 'D'.",
    "      WHEN 3. lv_lang = 'E'.",
    "    ENDCASE.",
    "    CASE lv_table.",
    "      WHEN 'T006'.",
    "        CLEAR: ls_t006, lo_t006.",
    "        READ TABLE lb_t006 INTO lo_t006 INDEX 1.",
    "        IF sy-subrc = 0.",
    "          lv_present = 'X'.",
    "          ls_t006 = lo_t006.",
    "        ENDIF.",
    "        GET REFERENCE OF ls_t006 INTO lr_row.",
    "        GET REFERENCE OF lo_t006 INTO lr_before.",
    "      WHEN 'T006A'.",
    "        CLEAR: ls_t006a, lo_t006a.",
    "        READ TABLE lb_t006a INTO lo_t006a",
    "          WITH KEY spras = lv_lang.",
    "        IF sy-subrc = 0.",
    "          lv_present = 'X'.",
    "          ls_t006a = lo_t006a.",
    "        ENDIF.",
    "        GET REFERENCE OF ls_t006a INTO lr_row.",
    "        GET REFERENCE OF lo_t006a INTO lr_before.",
    "      WHEN 'T006B'.",
    "        CLEAR: ls_t006b, lo_t006b.",
    "        READ TABLE lb_t006b INTO lo_t006b",
    "          WITH KEY spras = lv_lang.",
    "        IF sy-subrc = 0.",
    "          lv_present = 'X'.",
    "          ls_t006b = lo_t006b.",
    "        ENDIF.",
    "        GET REFERENCE OF ls_t006b INTO lr_row.",
    "        GET REFERENCE OF lo_t006b INTO lr_before.",
    "      WHEN 'T006C'.",
    "        CLEAR: ls_t006c, lo_t006c.",
    "        READ TABLE lb_t006c INTO lo_t006c",
    "          WITH KEY spras = lv_lang.",
    "        IF sy-subrc = 0.",
    "          lv_present = 'X'.",
    "          ls_t006c = lo_t006c.",
    "        ENDIF.",
    "        GET REFERENCE OF ls_t006c INTO lr_row.",
    "        GET REFERENCE OF lo_t006c INTO lr_before.",
    "      WHEN 'T006D'.",
    "        CLEAR: ls_t006d, lo_t006d.",
    "        READ TABLE lb_t006d INTO lo_t006d INDEX 1.",
    "        IF sy-subrc = 0.",
    "          lv_present = 'X'.",
    "          ls_t006d = lo_t006d.",
    "        ENDIF.",
    "        GET REFERENCE OF ls_t006d INTO lr_row.",
    "        GET REFERENCE OF lo_t006d INTO lr_before.",
    "    ENDCASE.",
    "    ASSIGN lr_row->* TO <row>.",
    "    ASSIGN lr_before->* TO <before>.",
    "    LOOP AT lt_fields INTO ls_field.",
    "      ASSIGN COMPONENT ls_field-fieldname OF STRUCTURE <row>",
    "        TO <value>.",
    "      IF sy-subrc <> 0.",
    "        ev_code = 'LAYOUT_CHANGED'.",
    "        RETURN.",
    "      ENDIF.",
    "      CLEAR: lv_value, lv_found, ls_value, ls_language.",
    "      READ TABLE lt_values INTO ls_value WITH KEY",
    "        tablename = lv_table recnumber = 1",
    "        fieldname = ls_field-fieldname.",
    "      IF sy-subrc = 0.",
    "        lv_found = 'X'.",
    "        lv_value = ls_value-value.",
    "      ENDIF.",
    "      IF lv_rows = 3.",
    "        READ TABLE lt_languages INTO ls_language WITH KEY",
    "          tablename = lv_table recnumber = 1",
    "          fieldname = ls_field-fieldname langu = lv_lang.",
    "        IF sy-subrc = 0.",
    "          lv_found = 'X'.",
    "          lv_value = ls_language-value.",
    "        ENDIF.",
    "      ENDIF.",
    "      IF ls_field-fieldname = 'MANDT'.",
    "        lv_value = sy-mandt.",
    "        lv_found = 'X'.",
    "      ELSEIF ls_field-fieldname = 'SPRAS' AND lv_rows = 3.",
    "        lv_value = lv_lang.",
    "        lv_found = 'X'.",
    "      ENDIF.",
    "      IF ls_field-keyflag = 'X' AND lv_found IS INITIAL.",
    "        ev_code = 'KEY_MISSING'.",
    "        RETURN.",
    "      ENDIF.",
    "      IF lv_found = 'X'.",
    "        IF ls_field-keyflag IS INITIAL",
    "        AND ( ls_value-flag <> 'USE' AND ls_language-flag <> 'USE' ).",
    "          ev_code = 'SOURCE_FLAG_UNSUPPORTED'.",
    "          RETURN.",
    "        ENDIF.",
    "        ev_error_field = ls_field-fieldname.",
    "        TRY.",
    "          CASE ls_field-inttype.",
    "            WHEN 'C'.",
    "              DESCRIBE FIELD <value> LENGTH lv_length",
    "                IN CHARACTER MODE.",
    "              IF strlen( lv_value ) > lv_length.",
    "                ev_code = 'VALUE_TRUNCATED'.",
    "                RETURN.",
    "              ENDIF.",
    "              <value> = lv_value.",
    "            WHEN 'N'.",
    "              IF lv_value CN '0123456789 '.",
    "                ev_code = 'CONVERSION_FAILED'.",
    "                RETURN.",
    "              ENDIF.",
    "              <value> = lv_value.",
    "            WHEN 'I' OR 'P' OR 'F' OR 's' OR 'b'.",
    "              IF ls_field-convexit IS NOT INITIAL.",
    "                ev_code = 'CONVERSION_EXIT_UNREVIEWED'.",
    "                RETURN.",
    "              ENDIF.",
    "              CALL FUNCTION 'SCPR_CT_DECDELIM_CONVERT_ONE'",
    "                EXPORTING decimals = ls_field-decimals",
    "                  datatype = ls_field-datatype",
    "                CHANGING value = lv_value",
    "                EXCEPTIONS error_message = 1 OTHERS = 2.",
    "              IF sy-subrc <> 0.",
    "                ev_code = 'CONVERSION_FAILED'.",
    "                RETURN.",
    "              ENDIF.",
    "              CLEAR ls_convert.",
    "              ls_convert-active = 'X'.",
    "              ls_convert-olength = ls_field-outputlen.",
    "              ls_convert-decimals = ls_field-decimals.",
    "              ls_convert-sign = ls_field-sign.",
    "              IF ls_field-inttype = 'F'.",
    "                ls_convert-sign = 'X'.",
    "              ENDIF.",
    "              CALL FUNCTION 'RS_CONV_EX_2_IN_NO_DD'",
    "                EXPORTING input_external = lv_value",
    "                  convert = ls_convert",
    "                IMPORTING output_internal = <value>",
    "                EXCEPTIONS error_message = 1 OTHERS = 2.",
    "              IF sy-subrc <> 0.",
    "                ev_code = 'CONVERSION_FAILED'.",
    "                RETURN.",
    "              ENDIF.",
    "          ENDCASE.",
    "        CATCH cx_root.",
    "          ev_code = 'CONVERSION_FAILED'.",
    "          RETURN.",
    "        ENDTRY.",
    "      ENDIF.",
    "      ASSIGN COMPONENT ls_field-fieldname OF STRUCTURE <before>",
    "        TO <old>.",
    "      IF sy-subrc <> 0.",
    "        ev_code = 'LAYOUT_CHANGED'.",
    "        RETURN.",
    "      ENDIF.",
    "      IF lv_present IS INITIAL.",
    "        lv_status = 'NEW'.",
    "      ELSEIF <value> = <old>.",
    "        lv_status = 'EQL'.",
    "      ELSE.",
    "        lv_status = 'CHG'.",
    "      ENDIF.",
    "      CONCATENATE lv_diffs lv_table ':' lv_index ':'",
    "        ls_field-fieldname ':' lv_status ';' INTO lv_diffs.",
    "    ENDLOOP.",
    "    CASE lv_table.",
    "      WHEN 'T006'. APPEND ls_t006 TO lt_t006.",
    "      WHEN 'T006A'. APPEND ls_t006a TO lt_t006a.",
    "      WHEN 'T006B'. APPEND ls_t006b TO lt_t006b.",
    "      WHEN 'T006C'. APPEND ls_t006c TO lt_t006c.",
    "      WHEN 'T006D'. APPEND ls_t006d TO lt_t006d.",
    "    ENDCASE.",
    "  ENDDO.",
    "ENDDO.",
    '" 双版本复读拒绝漂移；用户小数格式也绑定到候选版本。',
    "CALL FUNCTION 'Z_ORVANTA_CFG_BC_READ'",
    "  EXPORTING iv_bc_set = iv_bc_set iv_version = iv_version",
    "  IMPORTING ev_code = lv_code ev_system = lv_system",
    "    ev_client = lv_client ev_user = lv_user",
    "    ev_source_version = lv_source ev_target_version = lv_target",
    "  TABLES et_t006 = lb_t006 et_t006a = lb_t006a",
    "    et_t006b = lb_t006b et_t006c = lb_t006c et_t006d = lb_t006d",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_code <> 'READ_OK'.",
    "  ev_code = 'READ_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "IF lv_source <> iv_source_version OR lv_target <> iv_target_version",
    "OR lv_system <> 'GR2' OR lv_client <> '200' OR lv_user <> sy-uname.",
    "  ev_code = 'VERSION_CONFLICT'.",
    "  RETURN.",
    "ENDIF.",
    "SELECT SINGLE dcpfm INTO lv_dcpfm_after FROM usr01",
    "  WHERE bname = sy-uname.",
    "IF sy-subrc <> 0 OR lv_dcpfm_after <> lv_dcpfm.",
    "  ev_code = 'USER_FORMAT_CHANGED'.",
    "  RETURN.",
    "ENDIF.",
    "EXPORT namespace = 'ORVANTA_BC_PREVIEW_V1'",
    "  system = sy-sysid client = sy-mandt user = sy-uname",
    "  source = lv_source target = lv_target format = lv_dcpfm",
    "  policy = 'CREATE_INITIAL_OR_UPDATE_USE'",
    "  unit = lt_t006 texts = lt_t006a commercial = lt_t006b",
    "  technical = lt_t006c dimension = lt_t006d diffs = lv_diffs",
    "  TO DATA BUFFER lv_buffer.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_buffer",
    "  IMPORTING hashstring = lv_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "    error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "TRANSLATE lv_hash TO LOWER CASE.",
    "IF strlen( lv_hash ) <> 64 OR lv_hash CN '0123456789abcdef'.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "et_t006[] = lt_t006[].",
    "et_t006a[] = lt_t006a[].",
    "et_t006b[] = lt_t006b[].",
    "et_t006c[] = lt_t006c[].",
    "et_t006d[] = lt_t006d[].",
    "ev_source_version = lv_source.",
    "ev_target_version = lv_target.",
    "ev_candidate_version = lv_hash.",
    "ev_differences = lv_diffs.",
    "CLEAR ev_error_field.",
    "ev_code = 'PREVIEW_OK'."
  ]
} as const
