import { configurationBcPreflightKeys } from "./configuration-bc-preflight.js"
import { configurationBcNativeLayouts } from "./configuration-bc-native-api.js"
import { configurationBcGuardLayouts } from "./configuration-bc-guard-api.js"
import {
  configurationBcStateTables,
  configurationBcStateLayoutFingerprint
} from "./configuration-bc-state-api.js"

const versions = ["SOURCE", "TARGET", "CANDIDATE", "METADATA", "GUARD", "CTS"] as const
const bindings = [
  "namespace",
  "system",
  "client",
  "user",
  "bcset",
  "version",
  "request",
  "task",
  "layout",
  ...versions.map((v) => v.toLowerCase())
]
const layouts = { ...configurationBcNativeLayouts, ...configurationBcGuardLayouts }
const parameter = (name: string) => ({
  name,
  typeName: "STRING",
  optional: false,
  passByValue: true
})
const hash = (data: string, output: string) => [
  "  CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
  `    EXPORTING alg = 'SHA2' data = ${data}`,
  `    IMPORTING hashstring = ${output}`,
  "    EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
  "      error_message = 4 OTHERS = 5.",
  "  IF sy-subrc <> 0.",
  "    ev_code = 'HASH_FAILED'. RETURN.",
  "  ENDIF.",
  `  TRANSLATE ${output} TO LOWER CASE.`,
  `  IF strlen( ${output} ) <> 64`,
  `  OR ${output} CN '0123456789abcdef'.`,
  "    ev_code = 'HASH_FAILED'. RETURN.",
  "  ENDIF."
]

/** ECC 7.31 read-only conversion check; never invokes the record-maintenance API. */
export const configurationBcRecoveryCheckApi = {
  functionName: "Z_ORVANTA_CFG_BC_RCHECK",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: [
    "IV_BC_SET",
    "IV_VERSION",
    "IV_REQUEST",
    "IV_TASK",
    ...versions.map((v) => `IV_${v}_VERSION`),
    "IV_STATE_VERSION",
    "IV_DATA_BASE64"
  ].map(parameter),
  exportParameters: [
    "EV_CODE",
    "EV_SYSTEM",
    "EV_CLIENT",
    "EV_USER",
    "EV_STATE_VERSION",
    "EV_LAYOUT_VERSION",
    "EV_ROW_COUNTS",
    "EV_ROW_PROOFS",
    "EV_PROOF_BASE64",
    "EV_PROOF_VERSION",
    "EV_ROUNDTRIP"
  ].map(parameter),
  source: [
    "TYPE-POOLS scpr.",
    '" 只检查可信原生前态的恢复值转换，不维护记录或传输。',
    "DATA: lv_buffer TYPE xstring, lv_roundtrip TYPE xstring,",
    "      lv_before TYPE xstring, lv_after TYPE xstring,",
    "      lv_proof TYPE xstring, lv_hash TYPE string,",
    "      lv_before_hash TYPE string, lv_after_hash TYPE string,",
    "      lv_base64 TYPE string, lv_rows TYPE string,",
    "      lv_counts TYPE string, lv_text TYPE string,",
    "      lv_tabletext TYPE string,",
    "      lv_names TYPE string, lv_expected TYPE string,",
    "      lv_table TYPE tddat-tabname, lv_group TYPE tddat-cclass,",
    "      lv_index TYPE i, lv_present TYPE c, lv_only_key TYPE c,",
    "      lv_type TYPE c, lv_len TYPE i, lv_fields TYPE i,",
    "      lv_keys TYPE i, lv_keylen TYPE i,",
    "      lv_external TYPE scprvals-value,",
    "      ls_field TYPE scpr_flddescr, lt_fields TYPE scpr_flddescrs,",
    "      ls_value TYPE scprvals, lt_values TYPE scpr_vals_tab,",
    "      lr_row TYPE REF TO data, lr_copy TYPE REF TO data.",
    "FIELD-SYMBOLS: <row> TYPE any, <copy> TYPE any,",
    "               <value> TYPE any.",
    ...bindings.map((name) => `DATA lr_${name} TYPE string.`),
    ...configurationBcStateTables.flatMap((name) => {
      const n = name.toLowerCase()
      return [
        `DATA lt_${n} TYPE STANDARD TABLE OF ${n}.`,
        `DATA ls_${n} TYPE ${n}.`,
        `DATA lc_${n} TYPE ${n}.`,
        `DATA lv_${n} TYPE i.`
      ]
    }),
    "CLEAR: ev_code, ev_system, ev_client, ev_user,",
    "  ev_state_version, ev_layout_version, ev_row_counts,",
    "  ev_row_proofs, ev_proof_base64, ev_proof_version, ev_roundtrip.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'. RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N'",
    "OR iv_request <> 'GR2K923429' OR iv_task <> 'GR2K923430'",
    "OR strlen( iv_data_base64 ) < 4",
    "OR strlen( iv_data_base64 ) > 699052.",
    "  ev_code = 'INPUT_INVALID'. RETURN.",
    "ENDIF.",
    ...[...versions, "STATE"].flatMap((v) => [
      `IF strlen( iv_${v.toLowerCase()}_version ) <> 64`,
      `OR iv_${v.toLowerCase()}_version CN '0123456789abcdef'.`,
      "  ev_code = 'INPUT_INVALID'. RETURN.",
      "ENDIF."
    ]),
    '" 即使缓冲来自本地回执，也重新检查认证用户的九表读权限。',
    "DO 9 TIMES.",
    "  CASE sy-index.",
    ...configurationBcStateTables.map((name, i) => `    WHEN ${i + 1}. lv_table = '${name}'.`),
    "  ENDCASE.",
    "  CLEAR lv_group.",
    "  SELECT SINGLE cclass INTO lv_group FROM tddat",
    "    WHERE tabname = lv_table.",
    "  IF sy-subrc <> 0 OR lv_group IS INITIAL.",
    "    lv_group = '&NC&'.",
    "  ENDIF.",
    "  AUTHORITY-CHECK OBJECT 'S_TABU_DIS'",
    "    ID 'ACTVT' FIELD '03' ID 'DICBERCLS' FIELD lv_group.",
    "  IF sy-subrc <> 0.",
    "    AUTHORITY-CHECK OBJECT 'S_TABU_NAM'",
    "      ID 'ACTVT' FIELD '03' ID 'TABLE' FIELD lv_table.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'AUTHORIZATION_DENIED'. RETURN.",
    "    ENDIF.",
    "  ENDIF.",
    "ENDDO.",
    "CALL FUNCTION 'SCMS_BASE64_DECODE_STR'",
    "  EXPORTING input = iv_data_base64 unescape = space",
    "  IMPORTING output = lv_buffer",
    "  EXCEPTIONS failed = 1 error_message = 2 OTHERS = 3.",
    "IF sy-subrc <> 0 OR xstrlen( lv_buffer ) = 0",
    "OR xstrlen( lv_buffer ) > 524288.",
    "  ev_code = 'BUFFER_INVALID'. RETURN.",
    "ENDIF.",
    "CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'",
    "  EXPORTING input = lv_buffer IMPORTING output = lv_base64",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_base64 <> iv_data_base64.",
    "  ev_code = 'BUFFER_INVALID'. RETURN.",
    "ENDIF.",
    ...hash("lv_buffer", "lv_hash"),
    "IF lv_hash <> iv_state_version.",
    "  ev_code = 'BUFFER_INVALID'. RETURN.",
    "ENDIF.",
    '" 按 STATE 同一类型导入并重导出，拒绝错布局或缺失成员。',
    "TRY.",
    "  IMPORT",
    ...bindings.map((name) => `    ${name} = lr_${name}`),
    ...configurationBcStateTables.map(
      (name) => `    ${name.toLowerCase()} = lt_${name.toLowerCase()}`
    ),
    "    FROM DATA BUFFER lv_buffer.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'BUFFER_INVALID'. RETURN.",
    "  ENDIF.",
    "  EXPORT",
    ...bindings.map((name) => `    ${name} = lr_${name}`),
    ...configurationBcStateTables.map(
      (name) => `    ${name.toLowerCase()} = lt_${name.toLowerCase()}`
    ),
    "    TO DATA BUFFER lv_roundtrip.",
    "CATCH cx_root.",
    "  ev_code = 'BUFFER_INVALID'. RETURN.",
    "ENDTRY.",
    "IF lv_roundtrip <> lv_buffer.",
    "  ev_code = 'BUFFER_INVALID'. RETURN.",
    "ENDIF.",
    "IF lr_namespace <> 'ORVANTA_CUNI_STATE_V1'",
    "OR lr_system <> sy-sysid OR lr_client <> sy-mandt",
    "OR lr_user <> sy-uname OR lr_bcset <> iv_bc_set",
    "OR lr_version <> iv_version OR lr_request <> iv_request",
    "OR lr_task <> iv_task OR lr_layout <>",
    `  '${configurationBcStateLayoutFingerprint}'.`,
    "  ev_code = 'BINDING_INVALID'. RETURN.",
    "ENDIF.",
    ...versions.flatMap((v) => [
      `IF lr_${v.toLowerCase()} <> iv_${v.toLowerCase()}_version.`,
      "  ev_code = 'BINDING_INVALID'. RETURN.",
      "ENDIF."
    ]),
    ...configurationBcStateTables.flatMap((name) => [
      `DESCRIBE TABLE lt_${name.toLowerCase()} LINES lv_len.`,
      `IF lv_len > ${configurationBcPreflightKeys.filter((key) => key.tableName === name).length}.`,
      "  ev_code = 'ROW_SCOPE_INVALID'. RETURN.",
      "ENDIF."
    ]),
    "DO 19 TIMES.",
    "  lv_index = sy-index.",
    "  CLEAR: lv_present, lv_only_key.",
    "  CASE lv_index.",
    ...configurationBcPreflightKeys.flatMap(({ tableName, key }, i) => {
      const n = tableName.toLowerCase()
      const fields = layouts[tableName as keyof typeof layouts].fields.join(",")
      const parts = fields.match(/.{1,40}/g)!
      return [
        `    WHEN ${i + 1}.`,
        `      lv_table = '${tableName}'.`,
        ...(parts.length === 1
          ? [`      lv_expected = '${fields}'.`]
          : [
              "      CONCATENATE",
              ...parts.map((part) => `        '${part}'`),
              "        INTO lv_expected."
            ]),
        `      CLEAR: ls_${n}, lc_${n}.`,
        `      READ TABLE lt_${n} INTO ls_${n} WITH KEY`,
        ...Object.entries(key).map(
          ([field, value]) => `        ${field.toLowerCase()} = '${value}'`
        ),
        "        .",
        "      IF sy-subrc = 0.",
        `        ADD 1 TO lv_${n}. lv_present = 'X'.`,
        "      ELSE.",
        ...Object.entries(key).map(
          ([field, value]) => `        ls_${n}-${field.toLowerCase()} = '${value}'.`
        ),
        "      ENDIF.",
        `      GET REFERENCE OF ls_${n} INTO lr_row.`,
        `      GET REFERENCE OF lc_${n} INTO lr_copy.`
      ]
    }),
    "  ENDCASE.",
    "  ASSIGN lr_row->* TO <row>.",
    "  ASSIGN lr_copy->* TO <copy>.",
    "  IF lv_present IS INITIAL. lv_only_key = 'X'. ENDIF.",
    '" 用标准描述器及转换函数检查恢复值；缺行只重建删除键。',
    "  REFRESH: lt_fields, lt_values.",
    "  CALL FUNCTION 'SCPR_DB_TABLE_TABFLDDEF_GET'",
    "    EXPORTING tabname = lv_table",
    "    IMPORTING keylen = lv_keylen",
    "    TABLES fielddescr = lt_fields",
    "    EXCEPTIONS table_not_found = 1 ddif_internal_error = 2",
    "      error_message = 3 OTHERS = 4.",
    "  IF sy-subrc <> 0 OR lt_fields IS INITIAL",
    "  OR lv_keylen <= 0.",
    "    ev_code = 'DESCRIPTOR_FAILED'. RETURN.",
    "  ENDIF.",
    "  lv_fields = 0. lv_keys = 0. CLEAR lv_names.",
    "  TRY.",
    "    LOOP AT lt_fields INTO ls_field.",
    "      ADD 1 TO lv_fields.",
    "      IF lv_names IS INITIAL. lv_names = ls_field-fieldname.",
    "      ELSE.",
    "        CONCATENATE lv_names ls_field-fieldname",
    "          INTO lv_names SEPARATED BY ','.",
    "      ENDIF.",
    "      IF ls_field-keyflag = 'X'. ADD 1 TO lv_keys. ENDIF.",
    "      ASSIGN COMPONENT ls_field-fieldname OF STRUCTURE <row>",
    "        TO <value>.",
    "      IF sy-subrc <> 0.",
    "        ev_code = 'DESCRIPTOR_FAILED'. RETURN.",
    "      ENDIF.",
    "      DESCRIBE FIELD <value> TYPE lv_type.",
    "      DESCRIBE FIELD <value> LENGTH lv_len IN BYTE MODE.",
    "      IF lv_type <> ls_field-vtype OR lv_len <> ls_field-intlen",
    "      OR lv_type NA 'CNDTIPFs' OR ls_field-maxbcslen > 255",
    "      OR ( lv_type = 's' AND",
    "        ( ls_field-datatype <> 'INT2' OR lv_len <> 2 ) )",
    "      OR ls_field-datatype = 'CURR'",
    "      OR ls_field-datatype = 'QUAN'",
    "      OR ls_field-readonly = 'R'.",
    "        ev_code = 'DESCRIPTOR_UNSUPPORTED'. RETURN.",
    "      ENDIF.",
    "      IF lv_only_key = 'X' AND ls_field-keyflag IS INITIAL.",
    "        CONTINUE.",
    "      ENDIF.",
    "      CLEAR lv_external.",
    "      CALL FUNCTION 'SCPR_CT_VALUE_CONVERT_INT_EXT'",
    "        EXPORTING fielddescr = ls_field value_intern = <value>",
    "          with_convexit = space",
    "        IMPORTING value_extern = lv_external",
    "        EXCEPTIONS error_message = 1 OTHERS = 2.",
    "      IF sy-subrc <> 0.",
    "        ev_code = 'CONVERSION_FAILED'. RETURN.",
    "      ENDIF.",
    "      CLEAR ls_value.",
    "      ls_value-id = iv_bc_set. ls_value-version = iv_version.",
    "      ls_value-tablename = lv_table. ls_value-recnumber = 1.",
    "      ls_value-fieldname = ls_field-fieldname.",
    "      ls_value-flag = ls_field-flag.",
    "      ls_value-value = lv_external.",
    "      APPEND ls_value TO lt_values.",
    "    ENDLOOP.",
    "    IF lv_names <> lv_expected OR lv_fields = 0 OR lv_keys = 0",
    "    OR lt_values IS INITIAL.",
    "      ev_code = 'DESCRIPTOR_FAILED'. RETURN.",
    "    ENDIF.",
    "    CALL FUNCTION 'SCPR_CPROF_CT_PROFDATA_CONVERT'",
    "      EXPORTING tabname = lv_table only_key = lv_only_key",
    "        recnumber = ls_value-recnumber keylen = lv_keylen",
    "        values_in_int_format = space",
    "      IMPORTING line = <copy>",
    "      TABLES profvalues = lt_values tabledescr = lt_fields",
    "      EXCEPTIONS error_message = 1 OTHERS = 2.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'CONVERSION_FAILED'. RETURN.",
    "    ENDIF.",
    '" 标准转换吞错或舍入时，原生结构比较必须失败。',
    "    EXPORT row = <row> TO DATA BUFFER lv_before.",
    "    EXPORT row = <copy> TO DATA BUFFER lv_after.",
    "  CATCH cx_root.",
    "    ev_code = 'CONVERSION_FAILED'. RETURN.",
    "  ENDTRY.",
    "  IF lv_before <> lv_after.",
    "    ev_code = 'ROUNDTRIP_LOSSY'. RETURN.",
    "  ENDIF.",
    ...hash("lv_before", "lv_before_hash"),
    ...hash("lv_after", "lv_after_hash"),
    "  lv_text = lv_index. CONDENSE lv_text NO-GAPS.",
    "  lv_tabletext = lv_table. CONDENSE lv_tabletext NO-GAPS.",
    "  IF lv_present IS INITIAL. lv_present = ' '. ENDIF.",
    "  CONCATENATE lv_text '|' lv_tabletext '|' lv_present '|'",
    "    lv_before_hash '|' lv_after_hash",
    "    INTO lv_text RESPECTING BLANKS.",
    "  IF lv_rows IS INITIAL. lv_rows = lv_text.",
    "  ELSE.",
    "    CONCATENATE lv_rows lv_text INTO lv_rows",
    "      SEPARATED BY cl_abap_char_utilities=>newline.",
    "  ENDIF.",
    "ENDDO.",
    '" 命中数量必须等于导入行数，拒绝重复或越出十九键的行。',
    ...configurationBcStateTables.flatMap((name) => {
      const n = name.toLowerCase()
      return [
        `DESCRIBE TABLE lt_${n} LINES lv_len.`,
        `IF lv_len <> lv_${n}.`,
        "  ev_code = 'ROW_SCOPE_INVALID'. RETURN.",
        "ENDIF.",
        "lv_text = lv_len. CONDENSE lv_text NO-GAPS.",
        `CONCATENATE lv_counts '${name}=' lv_text ';'`,
        "  INTO lv_counts."
      ]
    }),
    "EXPORT state = iv_state_version layout = lr_layout",
    "  system = lr_system client = lr_client user = lr_user",
    "  rows = lv_rows counts = lv_counts TO DATA BUFFER lv_proof.",
    ...hash("lv_proof", "lv_hash"),
    "CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'",
    "  EXPORTING input = lv_proof IMPORTING output = lv_base64",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_base64 IS INITIAL.",
    "  ev_code = 'ENCODING_FAILED'. RETURN.",
    "ENDIF.",
    '" 成功只证明本次转换，未建立锁内快照或写入/恢复许可。',
    "ev_system = sy-sysid. ev_client = sy-mandt. ev_user = sy-uname.",
    "ev_state_version = iv_state_version. ev_layout_version = lr_layout.",
    "ev_row_counts = lv_counts. ev_row_proofs = lv_rows.",
    "ev_proof_base64 = lv_base64. ev_proof_version = lv_hash.",
    "ev_roundtrip = 'X'. ev_code = 'RECOVERY_CHECK_OK'."
  ]
} as const
