import { createHash } from "node:crypto"
import { configurationBcPreflightKeys } from "./configuration-bc-preflight.js"

const parameter = (name: string) => ({
  name,
  typeName: "STRING",
  optional: false,
  passByValue: true
})
export const configurationBcEffectsLayouts = {
  SCPRACTR: "eee9c8994fbb082f7019d7f8f61c9f890e4652d4e55c56d27bacbb6c76ac9619",
  SCPRACTP: "7449a52bd3293c31ad419f2fd357d9974878b7a1a577406ca9f05947695946ff",
  SCPRACTX: "fc149745aa6d52a1c0f18d3b0b205323a4f9db8bb83a4b9a16b8193c1e979aa4",
  SCPRACTXL: "9775b093668a50ac579ebc81bfcaaddf85d5aca55a1bb701cab72aae008e547f"
} as const
export const configurationBcEffectsScope = createHash("sha256")
  .update(
    JSON.stringify({ keys: configurationBcPreflightKeys, layouts: configurationBcEffectsLayouts })
  )
  .digest("hex")
const tables = Object.keys(configurationBcEffectsLayouts)
const bindingNames = [
  "namespace",
  "system",
  "client",
  "user",
  "bcset",
  "version",
  "request",
  "task",
  "cts",
  "scope"
]
const tableBuffers = ["matched", "records", "headers", "variables", "links"]
const ctsCheck = [
  "  CALL FUNCTION 'Z_ORVANTA_CFG_BC_CTS'",
  "    EXPORTING iv_bc_set = iv_bc_set iv_version = iv_version",
  "      iv_request = iv_request iv_task = iv_task",
  "    IMPORTING ev_code = lv_code ev_system = lv_system",
  "      ev_client = lv_client ev_user = lv_user",
  "      ev_cts_version = lv_cts",
  "    EXCEPTIONS error_message = 1 OTHERS = 2.",
  "  IF sy-subrc <> 0 OR lv_code <> 'CTS_READ_OK' OR",
  "     lv_system <> sy-sysid",
  "  OR lv_client <> sy-mandt OR lv_user <> sy-uname.",
  "    ev_code = 'DEPENDENCY_FAILED'. RETURN.",
  "  ENDIF.",
  "  IF lv_cts <> iv_cts_version.",
  "    ev_code = 'VERSION_CONFLICT'. RETURN.",
  "  ENDIF."
]

/** Undeployed fixed-scope reader. No maintenance, locks, activation or recovery permission. */
export const configurationBcEffectsApi = {
  functionName: "Z_ORVANTA_CFG_BC_EFFECTS",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: ["IV_BC_SET", "IV_VERSION", "IV_REQUEST", "IV_TASK", "IV_CTS_VERSION"].map(
    parameter
  ),
  exportParameters: [
    "EV_CODE",
    "EV_SYSTEM",
    "EV_CLIENT",
    "EV_USER",
    "EV_REQUEST",
    "EV_TASK",
    "EV_CTS_VERSION",
    "EV_SCOPE_VERSION",
    "EV_EFFECTS_VERSION",
    "EV_ROW_COUNTS",
    "EV_PROFILE_COUNT",
    "EV_DATA_BASE64",
    "EV_DATA_BYTES",
    "EV_ROUNDTRIP"
  ].map(parameter),
  tableParameters: [],
  source: [
    '" 固定十九键的标准激活链接前态；只读，不授予恢复许可。',
    "TYPES: BEGIN OF ty_scope,",
    "  tablename TYPE scpractr-tablename,",
    "  tabkey TYPE scpractr-tabkey, END OF ty_scope.",
    "TYPES: BEGIN OF ty_profile,",
    "  id TYPE scpractr-profid, END OF ty_profile.",
    "DATA: lt_scope TYPE STANDARD TABLE OF ty_scope,",
    "      ls_scope TYPE ty_scope,",
    "      lt_profiles TYPE STANDARD TABLE OF ty_profile,",
    "      ls_profile TYPE ty_profile, ls_record TYPE scpractr,",
    "      ls_full_record TYPE scpractr,",
    "      lt_matched TYPE STANDARD TABLE OF scpractr,",
    "      lt_records TYPE STANDARD TABLE OF scpractr,",
    "      lt_headers TYPE STANDARD TABLE OF scpractp,",
    "      lt_variables TYPE STANDARD TABLE OF scpractx,",
    "      lt_links TYPE STANDARD TABLE OF scpractxl,",
    "      lv_table TYPE tddat-tabname, lv_group TYPE tddat-cclass,",
    "      lv_code TYPE string, lv_system TYPE string,",
    "      lv_client TYPE string, lv_user TYPE string,",
    "      lv_cts TYPE string, lv_scope TYPE string,",
    "      lv_namespace TYPE string, lv_hash TYPE string,",
    "      lv_counts TYPE string, lv_text TYPE string,",
    "      lv_base64 TYPE string, lv_buffer TYPE xstring,",
    "      lv_first TYPE xstring, lv_roundtrip TYPE xstring,",
    "      lv_index TYPE i, lv_pass TYPE i, lv_count TYPE i,",
    "      lv_profiles TYPE i, lv_offset TYPE i, lv_length TYPE i,",
    "      lv_type TYPE c, lv_expected TYPE scpractr-tabkey,",
    "      lr_row TYPE REF TO data.",
    "FIELD-SYMBOLS: <row> TYPE any, <value> TYPE any.",
    ...[...new Set(configurationBcPreflightKeys.map((k) => k.tableName))].map(
      (name) => `DATA ls_${name.toLowerCase()} TYPE ${name.toLowerCase()}.`
    ),
    ...bindingNames.map((name) => `DATA lr_${name} TYPE string.`),
    "DATA lr_keys TYPE STANDARD TABLE OF ty_scope.",
    ...tableBuffers.map(
      (name, i) =>
        `DATA lr_${name} TYPE STANDARD TABLE OF ${["scpractr", "scpractr", "scpractp", "scpractx", "scpractxl"][i]}.`
    ),
    "CLEAR: ev_code, ev_system, ev_client, ev_user, ev_request,",
    "  ev_task, ev_cts_version, ev_scope_version, ev_effects_version,",
    "  ev_row_counts, ev_profile_count, ev_data_base64,",
    "  ev_data_bytes, ev_roundtrip.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'. RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N' OR",
    "   iv_request <> 'GR2K923429' OR iv_task <> 'GR2K923430' OR",
    "   strlen( iv_cts_version ) <> 64 OR",
    "   iv_cts_version CN '0123456789abcdef'.",
    "  ev_code = 'INPUT_INVALID'. RETURN.",
    "ENDIF.",
    "DO 4 TIMES.",
    "  CASE sy-index.",
    ...tables.map((name, i) => `    WHEN ${i + 1}. lv_table = '${name}'.`),
    "  ENDCASE.",
    "  CLEAR lv_group.",
    "  SELECT SINGLE cclass FROM tddat INTO lv_group",
    "    WHERE tabname = lv_table.",
    "  IF sy-subrc <> 0 OR lv_group IS INITIAL.",
    "    lv_group = '&NC&'.",
    "  ENDIF.",
    "  AUTHORITY-CHECK OBJECT 'S_TABU_DIS'",
    "    ID 'DICBERCLS' FIELD lv_group ID 'ACTVT' FIELD '03'.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'AUTHORIZATION_DENIED'. RETURN.",
    "  ENDIF.",
    "ENDDO.",
    "TRY.",
    '" 标准函数缓存描述器；以本次DDIC结构的字符键再核对其结果。',
    "  DO 19 TIMES.",
    "    lv_index = sy-index. CLEAR: ls_scope, lv_expected.",
    "    lv_offset = 0.",
    "    CASE lv_index.",
    ...configurationBcPreflightKeys.flatMap(({ tableName, key }, i) => {
      const n = tableName.toLowerCase()
      return [
        `      WHEN ${i + 1}.`,
        `        ls_scope-tablename = '${tableName}'.`,
        `        CLEAR ls_${n}.`,
        ...Object.entries(key).map(
          ([field, value]) => `        ls_${n}-${field.toLowerCase()} = '${value}'.`
        ),
        `        GET REFERENCE OF ls_${n} INTO lr_row.`,
        ...Object.keys(key).flatMap((field) => [
          `        DESCRIBE FIELD ls_${n}-${field.toLowerCase()} TYPE lv_type.`,
          `        DESCRIBE FIELD ls_${n}-${field.toLowerCase()}`,
          "          LENGTH lv_length IN CHARACTER MODE.",
          "        IF lv_type NA 'CN' OR lv_length <= 0 OR",
          "           lv_offset + lv_length > 255.",
          "          ev_code = 'KEY_SCOPE_FAILED'. RETURN.",
          "        ENDIF.",
          `        lv_expected+lv_offset(lv_length) =`,
          `          ls_${n}-${field.toLowerCase()}.`,
          "        ADD lv_length TO lv_offset."
        ])
      ]
    }),
    "    ENDCASE.",
    "    ASSIGN lr_row->* TO <row>.",
    "    CALL FUNCTION 'SCPR_HI_KEY_TO_ACTKEY'",
    "      EXPORTING tablename = ls_scope-tablename key = <row>",
    "      IMPORTING tablekey = ls_scope-tabkey",
    "      EXCEPTIONS wrong_parameters = 1 key_too_large = 2",
    "        fielddescr_error = 3 error_message = 4 OTHERS = 5.",
    "    IF sy-subrc <> 0 OR ls_scope-tabkey <> lv_expected.",
    "      ev_code = 'KEY_SCOPE_FAILED'. RETURN.",
    "    ENDIF.",
    "    APPEND ls_scope TO lt_scope.",
    "  ENDDO.",
    "  SORT lt_scope BY tablename tabkey.",
    "  DELETE ADJACENT DUPLICATES FROM lt_scope COMPARING ALL FIELDS.",
    "  DESCRIBE TABLE lt_scope LINES lv_count.",
    "  IF lv_count <> 19.",
    "    ev_code = 'KEY_SCOPE_FAILED'. RETURN.",
    "  ENDIF.",
    "  lv_namespace = 'ORVANTA_CUNI_EFFECTS_V1'.",
    `  lv_scope = '${configurationBcEffectsScope.slice(0, 32)}'.`,
    `  CONCATENATE lv_scope '${configurationBcEffectsScope.slice(32)}'`,
    "    INTO lv_scope.",
    "  DO 2 TIMES.",
    "    lv_pass = sy-index.",
    ...ctsCheck,
    '" 仅替换空VIEWNAME的表级链接；相关profile须包含全部既有链接。',
    "    SELECT * FROM scpractr UP TO 513 ROWS",
    "      INTO TABLE lt_matched FOR ALL ENTRIES IN lt_scope",
    "      WHERE tablename = lt_scope-tablename",
    "        AND tabkey = lt_scope-tabkey AND viewname = space.",
    "    IF sy-subrc <> 0 AND sy-subrc <> 4.",
    "      ev_code = 'READ_FAILED'. RETURN.",
    "    ENDIF.",
    "    DESCRIBE TABLE lt_matched LINES lv_count.",
    "    IF lv_count > 512.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    REFRESH lt_profiles. CLEAR ls_profile.",
    "    ls_profile-id = iv_bc_set. APPEND ls_profile TO lt_profiles.",
    "    LOOP AT lt_matched INTO ls_record.",
    "      IF ls_record-profid IS INITIAL.",
    "        ev_code = 'READ_FAILED'. RETURN.",
    "      ENDIF.",
    "      ls_profile-id = ls_record-profid.",
    "      APPEND ls_profile TO lt_profiles.",
    "    ENDLOOP.",
    "    SORT lt_profiles BY id.",
    "    DELETE ADJACENT DUPLICATES FROM lt_profiles COMPARING id.",
    "    DESCRIBE TABLE lt_profiles LINES lv_profiles.",
    "    IF lv_profiles = 0 OR lv_profiles > 32.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    ...[
      ["scpractr", "records", "profid"],
      ["scpractp", "headers", "profid"],
      ["scpractx", "variables", "profid"],
      ["scpractxl", "links", "bcset"]
    ].flatMap(([table, name, id]) => [
      `    SELECT * FROM ${table} UP TO 513 ROWS`,
      `      INTO TABLE lt_${name} FOR ALL ENTRIES IN lt_profiles`,
      `      WHERE ${id} = lt_profiles-id.`,
      "    IF sy-subrc <> 0 AND sy-subrc <> 4.",
      "      ev_code = 'READ_FAILED'. RETURN.",
      "    ENDIF.",
      `    DESCRIBE TABLE lt_${name} LINES lv_count.`,
      "    IF lv_count > 512.",
      "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
      "    ENDIF."
    ]),
    "    SORT lt_matched BY client tablename tabrecnumb.",
    "    SORT lt_records BY client tablename tabrecnumb.",
    "    SORT lt_headers BY client profid modifier.",
    "    SORT lt_variables BY client profid moddate modtime",
    "      dataelem oldvalue.",
    "    SORT lt_links BY client bcset moddate modtime tablename",
    "      recnumber fieldname langu.",
    "    LOOP AT lt_matched INTO ls_record.",
    "      READ TABLE lt_records INTO ls_full_record",
    "        WITH KEY client = ls_record-client",
    "        tablename = ls_record-tablename",
    "        tabrecnumb = ls_record-tabrecnumb BINARY SEARCH.",
    "      IF sy-subrc <> 0 OR ls_full_record <> ls_record.",
    "        ev_code = 'READ_CHANGED'. RETURN.",
    "      ENDIF.",
    "    ENDLOOP.",
    ...ctsCheck,
    "    EXPORT namespace = lv_namespace system = lv_system",
    "      client = lv_client user = lv_user bcset = iv_bc_set",
    "      version = iv_version request = iv_request task = iv_task",
    "      cts = lv_cts scope = lv_scope keys = lt_scope",
    "      matched = lt_matched records = lt_records",
    "      headers = lt_headers variables = lt_variables",
    "      links = lt_links TO DATA BUFFER lv_buffer.",
    "    IF xstrlen( lv_buffer ) = 0 OR",
    "       xstrlen( lv_buffer ) > 524288.",
    "      ev_code = 'LIMIT_EXCEEDED'. RETURN.",
    "    ENDIF.",
    "    IF lv_pass = 1. lv_first = lv_buffer.",
    "    ELSEIF lv_first <> lv_buffer.",
    "      ev_code = 'READ_CHANGED'. RETURN.",
    "    ENDIF.",
    "  ENDDO.",
    '" 原生IMPORT/EXPORT比较保留空格、日期时间、缺行与全部字段。',
    "  IMPORT namespace = lr_namespace system = lr_system",
    "    client = lr_client user = lr_user bcset = lr_bcset",
    "    version = lr_version request = lr_request task = lr_task",
    "    cts = lr_cts scope = lr_scope keys = lr_keys",
    "    matched = lr_matched records = lr_records",
    "    headers = lr_headers variables = lr_variables",
    "    links = lr_links FROM DATA BUFFER lv_buffer.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'ROUNDTRIP_FAILED'. RETURN.",
    "  ENDIF.",
    "  EXPORT namespace = lr_namespace system = lr_system",
    "    client = lr_client user = lr_user bcset = lr_bcset",
    "    version = lr_version request = lr_request task = lr_task",
    "    cts = lr_cts scope = lr_scope keys = lr_keys",
    "    matched = lr_matched records = lr_records",
    "    headers = lr_headers variables = lr_variables",
    "    links = lr_links TO DATA BUFFER lv_roundtrip.",
    "  IF lv_roundtrip <> lv_buffer.",
    "    ev_code = 'ROUNDTRIP_FAILED'. RETURN.",
    "  ENDIF.",
    "CATCH cx_root.",
    "  ev_code = 'READ_FAILED'. RETURN.",
    "ENDTRY.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_buffer",
    "  IMPORTING hashstring = lv_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "    error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'. RETURN.",
    "ENDIF.",
    "TRANSLATE lv_hash TO LOWER CASE.",
    "IF strlen( lv_hash ) <> 64 OR lv_hash CN '0123456789abcdef'.",
    "  ev_code = 'HASH_FAILED'. RETURN.",
    "ENDIF.",
    "CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'",
    "  EXPORTING input = lv_buffer IMPORTING output = lv_base64",
    "  EXCEPTIONS error_message = 1 OTHERS = 2.",
    "IF sy-subrc <> 0 OR lv_base64 IS INITIAL.",
    "  ev_code = 'ENCODING_FAILED'. RETURN.",
    "ENDIF.",
    "CLEAR lv_counts.",
    ...tableBuffers.flatMap((name) => [
      `DESCRIBE TABLE lt_${name} LINES lv_count.`,
      "lv_text = lv_count. CONDENSE lv_text NO-GAPS.",
      `CONCATENATE lv_counts '${name}=' lv_text ';' INTO lv_counts.`
    ]),
    "ev_system = sy-sysid. ev_client = sy-mandt. ev_user = sy-uname.",
    "ev_request = iv_request. ev_task = iv_task.",
    "ev_cts_version = lv_cts. ev_scope_version = lv_scope.",
    "ev_effects_version = lv_hash. ev_row_counts = lv_counts.",
    "ev_profile_count = lv_profiles. CONDENSE ev_profile_count NO-GAPS.",
    "ev_data_bytes = xstrlen( lv_buffer ).",
    "CONDENSE ev_data_bytes NO-GAPS.",
    "ev_data_base64 = lv_base64. ev_roundtrip = 'X'.",
    "ev_code = 'EFFECTS_READ_OK'."
  ]
} as const
