// ECC 7.31 deployment candidate: CUNI/T metadata only; never invokes methods.
export const configurationBcRouteApi = {
  functionName: "Z_ORVANTA_CFG_BC_ROUTE",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: [
    {
      name: "IV_BC_SET",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_SOURCE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_TARGET_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  exportParameters: [
    {
      name: "EV_CODE",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SYSTEM",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_CLIENT",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_USER",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SOURCE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_TARGET_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_METADATA_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  tableParameters: [
    {
      name: "ET_OBJH",
      typeName: "OBJH",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_OBJS",
      typeName: "OBJS",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_OBJM",
      typeName: "OBJM",
      optional: false,
      passByValue: false
    }
  ],
  source: [
    "DATA: ls_header TYPE objh,",
    "      lt_headers TYPE STANDARD TABLE OF objh,",
    "      lt_members TYPE STANDARD TABLE OF objs,",
    "      lt_methods TYPE STANDARD TABLE OF objm,",
    "      lv_table TYPE tddat-tabname, lv_group TYPE tddat-cclass,",
    "      lv_code TYPE string, lv_system TYPE string,",
    "      lv_client TYPE string, lv_user TYPE string,",
    "      lv_source TYPE string, lv_target TYPE string,",
    "      lv_buffer TYPE xstring, lv_first TYPE xstring,",
    "      lv_hash TYPE string, lv_count TYPE i, lv_pass TYPE i,",
    "      lt_t006 TYPE STANDARD TABLE OF t006,",
    "      lt_t006a TYPE STANDARD TABLE OF t006a,",
    "      lt_t006b TYPE STANDARD TABLE OF t006b,",
    "      lt_t006c TYPE STANDARD TABLE OF t006c,",
    "      lt_t006d TYPE STANDARD TABLE OF t006d.",
    '" 固定 CUNI/T 元数据读取；不调用任何动态方法或配置命令。',
    "CLEAR: ev_code, ev_system, ev_client, ev_user,",
    "       ev_source_version, ev_target_version, ev_metadata_version.",
    "REFRESH: et_objh, et_objs, et_objm.",
    "ev_system = sy-sysid.",
    "ev_client = sy-mandt.",
    "ev_user = sy-uname.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'.",
    "  RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N'",
    "OR strlen( iv_source_version ) <> 64",
    "OR iv_source_version CN '0123456789abcdef'",
    "OR strlen( iv_target_version ) <> 64",
    "OR iv_target_version CN '0123456789abcdef'.",
    "  ev_code = 'INPUT_INVALID'.",
    "  RETURN.",
    "ENDIF.",
    "IF iv_source_version <>",
    "  '73783f69f1bf9805b058fbc9bab0adb8cc8047f85c837ee16c174a9edd0f512b'.",
    "  ev_code = 'SOURCE_NOT_ATTESTED'.",
    "  RETURN.",
    "ENDIF.",
    '" 表名固定，逐表显示权限；沿用既有 READ 的授权模式。',
    "DO 3 TIMES.",
    "  CASE sy-index.",
    "    WHEN 1. lv_table = 'OBJH'.",
    "    WHEN 2. lv_table = 'OBJS'.",
    "    WHEN 3. lv_table = 'OBJM'.",
    "  ENDCASE.",
    "  CLEAR lv_group.",
    "  SELECT SINGLE cclass INTO lv_group FROM tddat",
    "    WHERE tabname = lv_table.",
    "  IF sy-subrc <> 0 OR lv_group IS INITIAL.",
    "    lv_group = '&NC&'.",
    "  ENDIF.",
    "  AUTHORITY-CHECK OBJECT 'S_TABU_DIS'",
    "    ID 'ACTVT' FIELD '03' ID 'DICBERCLS' FIELD lv_group.",
    "  IF sy-subrc <> 0.",
    "    AUTHORITY-CHECK OBJECT 'S_TABU_NAM'",
    "      ID 'ACTVT' FIELD '03' ID 'TABLE' FIELD lv_table.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'AUTHORIZATION_DENIED'.",
    "      RETURN.",
    "    ENDIF.",
    "  ENDIF.",
    "ENDDO.",
    '" 顺序双读不是锁定快照；任何变化都不返回可用元数据。',
    "DO 2 TIMES.",
    "  lv_pass = sy-index.",
    "  CALL FUNCTION 'Z_ORVANTA_CFG_BC_READ'",
    "    EXPORTING iv_bc_set = iv_bc_set iv_version = iv_version",
    "    IMPORTING ev_code = lv_code ev_system = lv_system",
    "      ev_client = lv_client ev_user = lv_user",
    "      ev_source_version = lv_source ev_target_version = lv_target",
    "    TABLES et_t006 = lt_t006 et_t006a = lt_t006a",
    "      et_t006b = lt_t006b et_t006c = lt_t006c et_t006d = lt_t006d",
    "    EXCEPTIONS error_message = 1 OTHERS = 2.",
    "  IF sy-subrc <> 0 OR lv_code <> 'READ_OK'.",
    "    ev_code = 'READ_FAILED'.",
    "    RETURN.",
    "  ENDIF.",
    "  IF lv_system <> sy-sysid OR lv_client <> sy-mandt",
    "  OR lv_user <> sy-uname OR lv_source <> iv_source_version",
    "  OR lv_target <> iv_target_version.",
    "    ev_code = 'VERSION_CONFLICT'.",
    "    RETURN.",
    "  ENDIF.",
    "  CLEAR ls_header.",
    "  SELECT SINGLE * INTO ls_header FROM objh",
    "    WHERE objectname = 'CUNI' AND objecttype = 'T'.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'OBJECT_NOT_DEFINED'.",
    "    RETURN.",
    "  ENDIF.",
    '  " 排除与执行路线无关的维护用户名和日期，避免外传个人信息。',
    "  CLEAR: ls_header-luser, ls_header-ldate.",
    "  REFRESH lt_headers.",
    "  APPEND ls_header TO lt_headers.",
    "  SELECT * FROM objs INTO TABLE lt_members UP TO 21 ROWS",
    "    WHERE objectname = 'CUNI' AND objecttype = 'T'.",
    "  IF sy-subrc <> 0 AND sy-subrc <> 4.",
    "    ev_code = 'READ_FAILED'.",
    "    RETURN.",
    "  ENDIF.",
    "  DESCRIBE TABLE lt_members LINES lv_count.",
    "  IF lv_count > 20.",
    "    ev_code = 'MEMBER_LIMIT'.",
    "    RETURN.",
    "  ENDIF.",
    "  IF lv_count = 0.",
    "    ev_code = 'MEMBERS_MISSING'.",
    "    RETURN.",
    "  ENDIF.",
    "  SELECT * FROM objm INTO TABLE lt_methods UP TO 11 ROWS",
    "    WHERE objectname = 'CUNI' AND objecttype = 'T'.",
    "  IF sy-subrc <> 0 AND sy-subrc <> 4.",
    "    ev_code = 'READ_FAILED'.",
    "    RETURN.",
    "  ENDIF.",
    "  DESCRIBE TABLE lt_methods LINES lv_count.",
    "  IF lv_count > 10.",
    "    ev_code = 'METHOD_LIMIT'.",
    "    RETURN.",
    "  ENDIF.",
    "  SORT lt_members BY objectname objecttype tabname.",
    "  SORT lt_methods BY objectname objecttype method.",
    "  EXPORT namespace = 'ORVANTA_CUNI_ROUTE_V1'",
    "    system = sy-sysid client = sy-mandt user = sy-uname",
    "    source = lv_source target = lv_target",
    "    headers = lt_headers members = lt_members methods = lt_methods",
    "    TO DATA BUFFER lv_buffer.",
    "  IF lv_pass = 1.",
    "    lv_first = lv_buffer.",
    "  ELSEIF lv_first <> lv_buffer.",
    "    ev_code = 'METADATA_CHANGED'.",
    "    RETURN.",
    "  ENDIF.",
    "ENDDO.",
    '" 双读之后再次核对完整源和目标版本，输出仍未填充。',
    "CALL FUNCTION 'Z_ORVANTA_CFG_BC_READ'",
    "    EXPORTING iv_bc_set = iv_bc_set iv_version = iv_version",
    "    IMPORTING ev_code = lv_code ev_system = lv_system",
    "      ev_client = lv_client ev_user = lv_user",
    "      ev_source_version = lv_source ev_target_version = lv_target",
    "    TABLES et_t006 = lt_t006 et_t006a = lt_t006a",
    "      et_t006b = lt_t006b et_t006c = lt_t006c et_t006d = lt_t006d",
    "    EXCEPTIONS error_message = 1 OTHERS = 2.",
    "  IF sy-subrc <> 0 OR lv_code <> 'READ_OK'.",
    "    ev_code = 'READ_FAILED'.",
    "    RETURN.",
    "  ENDIF.",
    "  IF lv_system <> sy-sysid OR lv_client <> sy-mandt",
    "  OR lv_user <> sy-uname OR lv_source <> iv_source_version",
    "  OR lv_target <> iv_target_version.",
    "    ev_code = 'VERSION_CONFLICT'.",
    "    RETURN.",
    "  ENDIF.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_buffer",
    "  IMPORTING hashstring = lv_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "    error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "TRANSLATE lv_hash TO LOWER CASE.",
    "IF strlen( lv_hash ) <> 64 OR lv_hash CN '0123456789abcdef'.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "et_objh[] = lt_headers[].",
    "et_objs[] = lt_members[].",
    "et_objm[] = lt_methods[].",
    "ev_source_version = lv_source.",
    "ev_target_version = lv_target.",
    "ev_metadata_version = lv_hash.",
    "ev_code = 'ROUTE_READ_OK'."
  ]
} as const
export const configurationBcRouteLayouts = {
  OBJH: {
    fields: [
      "OBJECTNAME",
      "OBJECTTYPE",
      "CLIDEP",
      "LANGDEP",
      "ALEDEP",
      "OBJCATEG",
      "TRCOMPLETE",
      "TRDISJUNCT",
      "PHASELEVEL",
      "LOCKMETH",
      "TADIRCMETH",
      "CHECKID",
      "OBJNAMELEN",
      "PROTECT",
      "OBJTRANSP",
      "LUSER",
      "LDATE",
      "OBJNAMECLS",
      "CURSETTING",
      "OBJHASADDR",
      "IMPORTABLE",
      "OBJCHARSET",
      "MCCATEGORY",
      "MCDOCUID"
    ],
    keys: ["OBJECTNAME", "OBJECTTYPE"],
    fingerprint: "fb45ff9f39ab443d5bf92b7240d9b0fe1dde165da1fea71a16026b045ac5c788"
  },
  OBJS: {
    fields: [
      "OBJECTNAME",
      "OBJECTTYPE",
      "TABNAME",
      "COVER",
      "CANDIDATE",
      "DDIC",
      "PRIM_TABLE",
      "VIEWGRANT",
      "TAB_FILLED"
    ],
    keys: ["OBJECTNAME", "OBJECTTYPE", "TABNAME"],
    fingerprint: "dc1667a4e14e0d69b372ef3a7704052d5456d0542b1d45390bb1a662a5723451"
  },
  OBJM: {
    fields: [
      "OBJECTNAME",
      "OBJECTTYPE",
      "METHOD",
      "METHODNAME",
      "UPGRADE",
      "MULTI_OBJ",
      "LANG_OBJ",
      "SHADOW_SYS"
    ],
    keys: ["OBJECTNAME", "OBJECTTYPE", "METHOD"],
    fingerprint: "95ffcd670dbcbc69d9aa8d53029b9e9456fe1663a71110ed15775445bea17d1a"
  }
} as const
