// Scoped ECC 7.31 deployment contract; creation does not imply runtime verification.
export const configurationBcNativeReadApi = {
  functionName: "Z_ORVANTA_CFG_BC_READ",
  functionGroup: "ZORVANTA_BC_CFG",
  remoteEnabled: true,
  importParameters: [
    {
      name: "IV_BC_SET",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "IV_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  exportParameters: [
    {
      name: "EV_CODE",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SYSTEM",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_CLIENT",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_USER",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_SOURCE_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    },
    {
      name: "EV_TARGET_VERSION",
      typeName: "STRING",
      optional: false,
      passByValue: true
    }
  ],
  tableParameters: [
    {
      name: "ET_T006",
      typeName: "T006",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006A",
      typeName: "T006A",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006B",
      typeName: "T006B",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006C",
      typeName: "T006C",
      optional: false,
      passByValue: false
    },
    {
      name: "ET_T006D",
      typeName: "T006D",
      optional: false,
      passByValue: false
    }
  ],
  source: [
    "DATA: ls_header TYPE scprattr,",
    "      ls_record TYPE scprreca,",
    "      lt_records TYPE STANDARD TABLE OF scprreca,",
    "      lt_values TYPE STANDARD TABLE OF scprvals,",
    "      lt_languages TYPE STANDARD TABLE OF scprvall,",
    "      lt_dependencies TYPE STANDARD TABLE OF scprpprl,",
    "      lt_t006 TYPE STANDARD TABLE OF t006,",
    "      lt_t006a TYPE STANDARD TABLE OF t006a,",
    "      lt_t006b TYPE STANDARD TABLE OF t006b,",
    "      lt_t006c TYPE STANDARD TABLE OF t006c,",
    "      lt_t006d TYPE STANDARD TABLE OF t006d,",
    "      lv_table TYPE tddat-tabname,",
    "      lv_group TYPE tddat-cclass,",
    "      lv_source TYPE xstring,",
    "      lv_target TYPE xstring,",
    "      lv_source_first TYPE xstring,",
    "      lv_target_first TYPE xstring,",
    "      lv_source_hash TYPE string,",
    "      lv_target_hash TYPE string,",
    "      lv_count TYPE i.",
    '" 每次初始化全部输出；失败不泄露前次调用的行或版本。',
    "CLEAR: ev_code, ev_system, ev_client, ev_user,",
    "       ev_source_version, ev_target_version.",
    "REFRESH et_t006.",
    "REFRESH et_t006a.",
    "REFRESH et_t006b.",
    "REFRESH et_t006c.",
    "REFRESH et_t006d.",
    "ev_system = sy-sysid.",
    "ev_client = sy-mandt.",
    "ev_user = sy-uname.",
    "IF sy-sysid <> 'GR2' OR sy-mandt <> '200'.",
    "  ev_code = 'SCOPE_UNSUPPORTED'.",
    "  RETURN.",
    "ENDIF.",
    "IF iv_bc_set <> 'EHS_CUNI_KNM' OR iv_version <> 'N'.",
    "  ev_code = 'INPUT_INVALID'.",
    "  RETURN.",
    "ENDIF.",
    '" 逐表验证读取权限；没有授权组时沿用 &NC&，名称权限可替代组权限。',
    "DO 10 TIMES.",
    "  CASE sy-index.",
    "    WHEN 1. lv_table = 'T006'.",
    "    WHEN 2. lv_table = 'T006A'.",
    "    WHEN 3. lv_table = 'T006B'.",
    "    WHEN 4. lv_table = 'T006C'.",
    "    WHEN 5. lv_table = 'T006D'.",
    "    WHEN 6. lv_table = 'SCPRATTR'.",
    "    WHEN 7. lv_table = 'SCPRRECA'.",
    "    WHEN 8. lv_table = 'SCPRVALS'.",
    "    WHEN 9. lv_table = 'SCPRVALL'.",
    "    WHEN 10. lv_table = 'SCPRPPRL'.",
    "  ENDCASE.",
    "  CLEAR lv_group.",
    "  SELECT SINGLE cclass INTO lv_group FROM tddat",
    "    WHERE tabname = lv_table.",
    "  IF sy-subrc <> 0 OR lv_group IS INITIAL.",
    "    lv_group = '&NC&'.",
    "  ENDIF.",
    "  AUTHORITY-CHECK OBJECT 'S_TABU_DIS'",
    "    ID 'ACTVT' FIELD '03' ID 'DICBERCLS' FIELD lv_group.",
    "  IF sy-subrc <> 0.",
    "    AUTHORITY-CHECK OBJECT 'S_TABU_NAM'",
    "      ID 'ACTVT' FIELD '03' ID 'TABLE' FIELD lv_table.",
    "    IF sy-subrc <> 0.",
    "      ev_code = 'AUTHORIZATION_DENIED'.",
    "      RETURN.",
    "    ENDIF.",
    "  ENDIF.",
    "ENDDO.",
    '" 两轮完整读取并比较原生缓冲；这是顺序观察，不是加锁快照。',
    "DO 2 TIMES.",
    "  SELECT SINGLE * INTO ls_header FROM scprattr",
    "    WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "  IF sy-subrc <> 0.",
    "    ev_code = 'SOURCE_NOT_FOUND'.",
    "    RETURN.",
    "  ENDIF.",
    "  IF ls_header-category IS NOT INITIAL OR ls_header-type <> 'TMV'.",
    "    ev_code = 'SOURCE_SCOPE_INVALID'.",
    "    RETURN.",
    "  ENDIF.",
    "  SELECT * FROM scprreca INTO TABLE lt_records UP TO 6 ROWS",
    "    WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "  DESCRIBE TABLE lt_records LINES lv_count.",
    "  IF lv_count <> 5.",
    "    ev_code = 'SOURCE_SCOPE_INVALID'.",
    "    RETURN.",
    "  ENDIF.",
    "  SORT lt_records BY id version tablename recnumber.",
    "  LOOP AT lt_records INTO ls_record.",
    "    CASE sy-tabix.",
    "      WHEN 1. lv_table = 'T006'.",
    "      WHEN 2. lv_table = 'T006A'.",
    "      WHEN 3. lv_table = 'T006B'.",
    "      WHEN 4. lv_table = 'T006C'.",
    "      WHEN 5. lv_table = 'T006D'.",
    "    ENDCASE.",
    "    IF ls_record-tablename <> lv_table OR ls_record-recnumber <> 1",
    "    OR ls_record-objectname <> 'CUNI' OR ls_record-objecttype <> 'T'",
    "    OR ls_record-deleteflag IS NOT INITIAL",
    "    OR ls_record-uncomplete IS NOT INITIAL",
    "    OR ls_record-genref IS NOT INITIAL",
    "    OR ls_record-activity IS NOT INITIAL",
    "    OR ls_record-clustname IS NOT INITIAL.",
    "      ev_code = 'SOURCE_SCOPE_INVALID'.",
    "      RETURN.",
    "    ENDIF.",
    "  ENDLOOP.",
    "  SELECT * FROM scprvals INTO TABLE lt_values UP TO 101 ROWS",
    "    WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "  DESCRIBE TABLE lt_values LINES lv_count.",
    "  IF lv_count > 100.",
    "    ev_code = 'SOURCE_LIMIT_EXCEEDED'.",
    "    RETURN.",
    "  ENDIF.",
    "  SORT lt_values BY id version tablename recnumber fieldname.",
    "  SELECT * FROM scprvall INTO TABLE lt_languages UP TO 101 ROWS",
    "    WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "  DESCRIBE TABLE lt_languages LINES lv_count.",
    "  IF lv_count > 100.",
    "    ev_code = 'SOURCE_LIMIT_EXCEEDED'.",
    "    RETURN.",
    "  ENDIF.",
    "  SORT lt_languages BY id version tablename recnumber fieldname langu.",
    "  SELECT * FROM scprpprl INTO TABLE lt_dependencies UP TO 1 ROWS",
    "    WHERE id = 'EHS_CUNI_KNM' AND version = 'N'.",
    "  IF lt_dependencies IS NOT INITIAL.",
    "    ev_code = 'SOURCE_SCOPE_INVALID'.",
    "    RETURN.",
    "  ENDIF.",
    "  SELECT * FROM t006 INTO TABLE lt_t006 WHERE msehi = 'KNM'.",
    "  SELECT * FROM t006a INTO TABLE lt_t006a WHERE msehi = 'KNM'",
    "    AND ( spras = '1' OR spras = 'D' OR spras = 'E' ).",
    '  " 别名按自身键读取；映射到其他单位的冲突也必须返回。',
    "  SELECT * FROM t006b INTO TABLE lt_t006b WHERE mseh3 = 'KNM'",
    "    AND ( spras = '1' OR spras = 'D' OR spras = 'E' ).",
    "  SELECT * FROM t006c INTO TABLE lt_t006c WHERE mseh6 = 'kN/m2'",
    "    AND ( spras = '1' OR spras = 'D' OR spras = 'E' ).",
    '  " PRESS 是共享维度；这里只读取完整行，不做保存。',
    "  SELECT * FROM t006d INTO TABLE lt_t006d WHERE dimid = 'PRESS'.",
    "  SORT lt_t006 BY mandt msehi.",
    "  SORT lt_t006a BY mandt spras msehi.",
    "  SORT lt_t006b BY mandt spras mseh3.",
    "  SORT lt_t006c BY mandt spras mseh6.",
    "  SORT lt_t006d BY mandt dimid.",
    '  " 原生类型序列化包括 FLTP、空格和缺失行；不经显示文本重建。',
    "  EXPORT namespace = 'ORVANTA_BC_SOURCE_V1'",
    "    system = sy-sysid client = sy-mandt",
    "    header = ls_header records = lt_records values = lt_values",
    "    languages = lt_languages dependencies = lt_dependencies",
    "    TO DATA BUFFER lv_source.",
    "  EXPORT namespace = 'ORVANTA_BC_TARGET_V1'",
    "    system = sy-sysid client = sy-mandt user = sy-uname",
    "    bc_set = iv_bc_set version = iv_version",
    "    unit = lt_t006 texts = lt_t006a commercial = lt_t006b",
    "    technical = lt_t006c dimension = lt_t006d",
    "    TO DATA BUFFER lv_target.",
    "  IF sy-index = 1.",
    "    lv_source_first = lv_source.",
    "    lv_target_first = lv_target.",
    "  ELSEIF lv_source <> lv_source_first OR lv_target <> lv_target_first.",
    "    ev_code = 'READ_CHANGED'.",
    "    RETURN.",
    "  ENDIF.",
    "ENDDO.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_source",
    "  IMPORTING hashstring = lv_source_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "             error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "CALL FUNCTION 'CALCULATE_HASH_FOR_RAW'",
    "  EXPORTING alg = 'SHA2' data = lv_target",
    "  IMPORTING hashstring = lv_target_hash",
    "  EXCEPTIONS unknown_alg = 1 param_error = 2 internal_error = 3",
    "             error_message = 4 OTHERS = 5.",
    "IF sy-subrc <> 0.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "TRANSLATE lv_source_hash TO LOWER CASE.",
    "TRANSLATE lv_target_hash TO LOWER CASE.",
    "IF strlen( lv_source_hash ) <> 64 OR strlen( lv_target_hash ) <> 64",
    "OR lv_source_hash CN '0123456789abcdef'",
    "OR lv_target_hash CN '0123456789abcdef'.",
    "  ev_code = 'HASH_FAILED'.",
    "  RETURN.",
    "ENDIF.",
    "et_t006[] = lt_t006[].",
    "et_t006a[] = lt_t006a[].",
    "et_t006b[] = lt_t006b[].",
    "et_t006c[] = lt_t006c[].",
    "et_t006d[] = lt_t006d[].",
    "ev_source_version = lv_source_hash.",
    "ev_target_version = lv_target_hash.",
    "ev_code = 'READ_OK'."
  ]
} as const

export const configurationBcNativeLayouts = {
  T006: {
    fingerprint: "f50d5162d3ec4d68c98ac89c4701206ac771cd14d4c2c3303b8e3d7ba280aba7",
    fields: [
      "MANDT",
      "MSEHI",
      "KZEX3",
      "KZEX6",
      "ANDEC",
      "KZKEH",
      "KZWOB",
      "KZ1EH",
      "KZ2EH",
      "DIMID",
      "ZAEHL",
      "NENNR",
      "EXP10",
      "ADDKO",
      "EXPON",
      "DECAN",
      "ISOCODE",
      "PRIMARY",
      "TEMP_VALUE",
      "TEMP_UNIT",
      "FAMUNIT",
      "PRESS_VAL",
      "PRESS_UNIT"
    ]
  },
  T006A: {
    fingerprint: "4c66cca985d3bb01e38b02ff5085f3e595e9da3e22e50bc75b47878940d9383d",
    fields: ["MANDT", "SPRAS", "MSEHI", "MSEH3", "MSEH6", "MSEHT", "MSEHL"]
  },
  T006B: {
    fingerprint: "ab70255e75a3137279fe7138aecba6dea563ad9886455ecb6d28534a69bbd286",
    fields: ["MANDT", "SPRAS", "MSEH3", "MSEHI"]
  },
  T006C: {
    fingerprint: "b0b1f805571a82c34ee6ce4c157e6b4a5dacdfe76ed29da5805e8699ac6b8521",
    fields: ["MANDT", "SPRAS", "MSEH6", "MSEHI"]
  },
  T006D: {
    fingerprint: "b8c3a7317ae77355313a75ff37216a2899338b0b45c4753772810b9815e4b95f",
    fields: [
      "MANDT",
      "DIMID",
      "LENG",
      "MASS",
      "TIMEX",
      "ECURR",
      "TEMP",
      "MOLQU",
      "LIGHT",
      "MSSIE",
      "TEMP_DEP",
      "PRESS_DEP"
    ]
  },
  SCPRATTR: {
    fingerprint: "e71cc9c625de174074c7e3713a400495c6fd199abee368406f1ee86b2d2858dd",
    fields: [
      "ID",
      "VERSION",
      "MODDATE",
      "MODTIME",
      "MODIFIER",
      "TYPE",
      "CATEGORY",
      "CLI_DEP",
      "CLI_CAS",
      "REFTYPE",
      "REFNAME",
      "ORGID",
      "COMPONENT",
      "MINRELEASE",
      "MAXRELEASE",
      "STATE",
      "ACT_INFO"
    ]
  },
  SCPRRECA: {
    fingerprint: "38d95ebbb9da35412026d146cdf5e412b4aeb19574e85aecb4b13931ba846ad5",
    fields: [
      "ID",
      "VERSION",
      "TABLENAME",
      "RECNUMBER",
      "OBJECTNAME",
      "OBJECTTYPE",
      "ACTIVITY",
      "CLUSTNAME",
      "UNCOMPLETE",
      "DELETEFLAG",
      "GENREF"
    ]
  },
  SCPRVALS: {
    fingerprint: "cb9bbce6821a09c25d775ec1bc46c19a87aa77f6455e44f5760b977f0b6979da",
    fields: ["ID", "VERSION", "TABLENAME", "RECNUMBER", "FIELDNAME", "FLAG", "VALUE"]
  },
  SCPRVALL: {
    fingerprint: "e87e898cc060fc1d2d3355a57640a592e16640ab318ae49ba0d7427a33e5991d",
    fields: ["ID", "VERSION", "TABLENAME", "RECNUMBER", "FIELDNAME", "LANGU", "FLAG", "VALUE"]
  },
  SCPRPPRL: {
    fingerprint: "4288352732b34bf40017f3813126403187769a4b3e4fc81fc069c1beb429ff11",
    fields: ["ID", "VERSION", "SUBPROFILE", "PROF_POSIT"]
  }
} as const
