/**
 * The SAP-side carrier programs, and the one thing a service update cannot do.
 *
 * A helper body lives inside SAP. Updating, repackaging, reinstalling or restarting the MCP service
 * changes nothing about it: only the carrier program, run in SE38, replaces the deployed body. A
 * version-check verdict is therefore a statement about SAP, not about the service build.
 *
 * That distinction was learned the expensive way. A freshly packaged release was installed and the
 * same capability still reported `unsupported`, which reads like a broken release when the real
 * state is "the SAP-side deployment is still pending". The verdict alone cannot say that, so every
 * version-driven shortfall now carries a remedy that names the SAP-side step, and the operator is
 * never left to infer it from a release note.
 *
 * The program names are the carriers this repository generates.
 * `test/helper-carriers.test.ts` reads them back out of the generator scripts, so a renamed carrier
 * fails the suite instead of producing a remedy that points at a program nobody can run. A helper
 * with no entry has no generated carrier yet, and the remedy says so rather than inventing a name.
 */
export const HELPER_CARRIER_PROGRAMS: Readonly<Record<string, string>> = {
  Z_ORVANTA_MCP_DDIC_API: "ZORVANTA_MCP_DDIC_LOCK_DEPLOY",
  // The repository family (Z_ORVANTA_MCP_EXECUTE / Z_ORVANTA_MCP_DYNPRO_API) shares one body source
  // but not one deployed include: each function module self-describes with its own name in the
  // CAPABILITIES rows, so the 2.8 body needs one carrier per target
  // (scripts/generate-repository-carrier.mjs, docs/release-process.md section 7.2).
  Z_ORVANTA_MCP_EXECUTE: "ZORVANTA_MCP_EXEC_DEPLOY",
  Z_ORVANTA_MCP_DYNPRO_API: "ZORVANTA_MCP_DYNPRO_DEPLOY",
  // The maintenance helper is NOT in the self-write-protected core group: it lives in
  // ZORVANTA_MAINT and its body comes from scripts/maintenance-diagnostic-source.mjs, which
  // scripts/bootstrap-sap-helper.ps1 does not carry (it only knows LOG_READ, the two MCP_*_API
  // modules, MCP_EXECUTE and OPS_READ). Being outside the guard does not make it writable: on
  // SAP_BASIS 7.31 the ADT write to a function module's own source/main is refused with HTTP 423
  // (12 of the 12 attempts on 2026-09-18 that reached the write failed), and the in-SAP
  // WRITE_FUNCTION_SOURCE path needs a helper protocol the deployment does not have yet. Its
  // carrier is therefore a body-only report (scripts/generate-maintenance-carrier.mjs) that keeps
  // the deployed parameter interface and replaces only the implementation body.
  Z_ORVANTA_MAINT_READ: "ZORVANTA_MAINT_DEPLOY"
}

/**
 * What an operator must actually do to satisfy a helper requirement.
 *
 * Deliberately starts with the thing that does NOT work: the mistake this exists to prevent is
 * rebuilding or restarting the service and expecting the SAP side to change.
 */
export function helperDeploymentRemedy(helper: string, requiredProtocol: string): string {
  const carrier = HELPER_CARRIER_PROGRAMS[helper.trim().toUpperCase()]
  const step = carrier
    ? `run the ${requiredProtocol} carrier program ${carrier} in SE38 and press F8`
    : `run the ${requiredProtocol} carrier program generated by docs/release-process.md section 7 in SE38 and press F8`
  return (
    `Repackaging, reinstalling or restarting the MCP service cannot change the SAP-side helper ` +
    `protocol: the helper body lives in SAP. To satisfy this requirement, ${step}, then restart ` +
    `the MCP service and re-read the capability report.`
  )
}
